import Head from "next/head.js";
import Button from "@/components/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <Button theme="w-full primary">Primary</Button>
      </main>
    </>
  );
}
